version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: docker/prod/app.dockerfile
    environment:
      - "TZ=Europe/Rome"
    container_name: tic_tac_toe_app
    networks:
      - default

  web:
    build:
      context: ./
      dockerfile: docker/prod/web.dockerfile
    container_name: tic_tac_toe_web
    environment:
      - "TZ=Europe/Rome"
    ports:
      - 80:80
    networks:
      - default

networks:
  default:
    driver: bridge
