version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/app.dockerfile
      args:
        - USER
        - GID
        - USERID
        - OS
    environment:
      - "TZ=Europe/Rome"
    container_name: tic_tac_toe_app
    volumes:
      - ./src:/var/www
    networks:
      - default

  web:
    build:
      context: ./
      dockerfile: docker/dev/web.dockerfile
    container_name: tic_tac_toe_web
    environment:
      - "TZ=Europe/Rome"
    volumes:
      - ./src:/var/www
    ports:
      - 8080:80
    networks:
      - default

networks:
  default:
    driver: bridge
